# TESTI SOLO IN INGLESE (Anche se per convenzione le traduzioni ce le ho messe) #

startprivate:
  en: |
    <i><b>A Yo-Kai Watch medallium simulator</b>. 
    Catch as many yo kai as possible in groups!
    Add me in your group or type /help to see the guide</i>
  
  it: "-"

onlyingroups:
  en: "<i>You can use this command only in groups</i>"
  it: "-"

botaddedtogroup:
  en: "<i>Let's fill your medallium!\nType /help to see the full guide and set language:</i>"
  it: "-"

#############################################

## TEXTS ##

changedlanguage:
  "en": "Language set in English ğŸ‡¬ğŸ‡§"
  "it": "Lingua impostata in Italiano ğŸ‡®ğŸ‡¹"

showsettings:
  "en": "âš™ï¸ <b>Settings</b>\n<i>Select an option to change it (only if you are an admin)</i>"
  "it": "âš™ï¸ <b>Impostazioni</b>\n<i>Seleziona un opzione per modificarla (solo se sei amministratore)</i>"

showmedallium:
  "en":
    - "<i>Has opened his Medallium</i>\nğŸ“Š <b>Statistics:\n</b>"
    - "<b>\nğŸ¤ğŸ» Yo-Kai befriended:</b>"
    - "<b>\nğŸ¤ğŸ½ Last befriended:</b>"
    - "<b>\nğŸ’• Duplicates:</b>"
    - "<b>\nğŸ† Medallium completion:</b>"
  "it":
    - "<i>Ha aperto il suo Medallium</i>\nğŸ“Š <b>Statistiche:</b>\n"
    - "<b>\nğŸ¤ğŸ» Yo-Kai ottenuti:</b>"
    - "<b>\nğŸ¤ğŸ½ Ultimo ottenuto:</b>"
    - "<b>\nğŸ’• Doppioni:</b>"
    - "<b>\nğŸ† Medallium completato:</b>"
emptymedallium: 
  "en": "<i>Your medallium is still empty...\nLet's friend with some Yo-kai!</i>"
  "it": "<i>Il tuo medallium e' ancora vuoto... \nStringi amicizia con qualche Yo-kai!</i>"


yokainotfound: 
  "en": "<i>âš ï¸The Yo-kai's name is incorrect</i>"
  "it": "<i>âš ï¸ Il nome dello Yo-kai Ã¨ sbagliato</i>"
yokainotgot: 
  "en": "<i>âš ï¸ You haven't got this Yo-kai yet</i>"
  "it": "<i>âš ï¸ Non possiedi ancora questo Yo-kai</i>"
recipientnotfound:
  "en": "<i>âš ï¸ Username not found or incorrect</i>"
  "it": "<i>âš ï¸ Username non trovato o errato</i>"
ykgiftdone:
  "en": "Gifted!"
  "it": "Regalato!"
ykgiftguide:
  "en": "<b>Usage:</b>\n/ykgift {Username} {Yo-kai}"
  "it": "<b>Utilizzo:</b>\n/ykgift {Username} {Yo-kai}"


releaseguide:
  "en": <b>Usage:\n</b> /release {Yo-kai}"
  "it": "<b>Utilizzo:\n</b> /release {Yo-kai}"
releasedone:
  "en": "<i>has released Yo-kai:</i>"
  "it": "<i>ha rilasciato lo Yo-kai:</i>"


yokaispawnevent: 
  "en": "<i>A new Yo-kai has just spawned, guess its name!\nType /friend [Name] to befriend it!</i>"
  "it": "<i>Ã‰ apparso un nuovo Yo-kai, indovina il suo nome!\nDigita /friend [Nome] per stringerci amicizia!</i>"
friendguide: 
  "en": "<i>You can use it when a Yo-kai spawns\n</i><b>Usage:</b> /friend {Yo-kai}"
  "it": "<i>Puoi usarlo quando uno Yo-kai appare\n</i><b>Utilizzo:</b> /friend {yokai}"
yokaihasescaped: 
  "en": "<i>Oh no! The Yo kai is gone away...</i>"
  "it": "<i>Oh no! Lo yokai e' fuggito...</i>"
yokaifriended:
  "en": 
    - "<b>\nYo-Kai Rank: </b>"
    - "<b>\nKai earned: </b>" 
  "it": 
    - "<b>\nRango Yo-Kai: </b>"
    - "<b>\nKai ottenuti: </b>"


changespawnrange: 
  "en": "Select the random Yo-Kai <b>spawnrange</b>:"
  "it": "Seleziona il <b>range di spawning</b> degli Yo-Kai:"
spawnrangechanged:
  "en": "Yo-Kai spawnrange set to: "
  "it": "Range di spawn degli Yo-Kai impostato su: "
changelang: 
  "en": "Choose the <b>language</b> you want to set:"
  "it": "Scegli la <b>lingua</b> che vuoi impostare:"
showcontact: 
  "en": "<b>ğŸ’¬ Contact</b> the bot staff by:"
  "it": "<b>ğŸ’¬ Contatta</b> lo staff del bot tramite:"

showleaderboard:
  "en": "<b>ğŸ† The best Yo-Kai collectors\n\n</b>"
  "it": "<b>ğŸ† I miglior collezionisti di Yo-Kai\n\n</b>"

no_leaderboard:
  en: "<i>No leaderboard avaible...\nNo one has caught a Yo-Kai yet in this group!</i>"
  it: "<i>Nessuna classifica disponibile...\nNessuno ha ancora catturato uno Yo-Kai in questo gruppo!</i>"


showcrankakai:
  "en": |
    <i><b>ğŸ° CRANK-A-KAI </b></i>
    <i>Tribes Coins:  <b>25 Kai</b>
    1 Star Coin:  <b>30 Kai</b>
    5 Star and Special Coins:  <b>40 Kai</b></i>
  
  "it": |
    <i><b>ğŸ° SLOT-KAI </b></i>
    <i>Monete tribÃ¹:  <b>25 Kai</b>
    Moneta 1 stella:  <b>30 Kai</b>
    Moneta 5 stelle e Speciale:  <b>40 Kai</b></i>

crankakaiprize:
  "en": 
    - "<i>From the Crank-a-Kai came out...</i>"
    - "received it in his medallium"
  "it": 
    - "<i>Dalla Slot-Kai Ã¨ uscito...</i>"
    - "lo ha ricevuto nel suo medallium"

notenoughkai:
  "en": "âš ï¸ Not enough Kai-Dollars... Earn more!"
  "it": "âš ï¸ Kai-Dollari insufficienti... Guadagnane altri!"

showinventory:
  "en":
    - " | <i>Inventory ğŸ’¼</i>"
    - "<i>Kai got:</i>"
  "it":
    - " | <i>Inventario ğŸ’¼</i>"
    - "<i>Kai ottenuti:</i>"

flexguide:
  "en": "<b>Usage:</b>\n/flex {Yo-kai}"
  "it": "<b>Utilizzo:</b>\n/flex {Yo-kai}"

flexmessage:
  "en": 
    - "<i>is flexing his Yo-kai:</i>"
    - "<i>ğŸ†” Yo-kai ID:</i>"
    - "<i>âšœï¸ Yo-kai Rank:</i>"
    - "<i>ğŸ¤ğŸ½ In the group you have:</i>"
    - "<i>ğŸ’¬ Owners in this chat:</i>"
    - "<i>ğŸŒ Times taken globally:</i>"
  "it": 
    - "<i>sta flexando il suo Yo-kai:</i>"
    - "<i>ğŸ†” Yo-kai ID:</i>"
    - "<i>âšœï¸ Yo-kai di Rango:</i>"
    - "<i>ğŸ¤ğŸ½ Nel gruppo ne possiedi:</i>"
    - "<i>ğŸ’¬ Possessori in questa chat:</i>"
    - "<i>ğŸŒ Volte preso globalmente:</i>"


showguide: 
  "en": |
    <b>ğŸ“‹ YoKaiMedals Commands </b>
    __________________________________
    /medallium - <i>See your Yo-Kai collection</i>
    /inventory - <i>See your items and Kai earned</i>
    /friend [yokai] - <i>Get a Yo-Kai when it spawns</i>
    /ykgift [user] [yokai] - <i>Give a Yo-Kai to someone</i>
    /release [yokai] - <i>Release a Yo-Kai from your medallium</i>
    /flex [yokai] - <i>Flex your Yo-Kai in chat</i>
    /crankakai - <i>Obtain new Yo-Kai!</i>
    /leaderboard - <i>See the best Yo-Kai hunters</i>

    /settings - <i>Change langage and spawnrange settings</i>
    /contact - <i>Contact us for support or feedbacks</i> 

  "it": |
    <b>ğŸ“‹ Comandi di YoKaiMedals </b>
    ____________________________________
    /medallium - <i>Vedi la tua collezione</i>
    /inventario [yokai] - <i>Vedi i tuoi item e i Kai-Dollari</i>
    /ykgift [user] [yokai] - <i>Regala un tuo Yo-Kai a qualcuno</i>
    /rilascia [yokai] - <i>Rilascia uno Yo-Kai dal tuo medallium</i>
    /flex [yokai] - <i>Flexa il tuo Yo-Kai in chat</i>
    /slotkai - <i>Ottieni nuovi Yo-Kai!</i>
    /classifica - <i>Vedi i migliori cacciatori di Yo-Kai</i>

    /settings - <i>Cambia la lingua e lo spawnrange</i>
    /contact - <i>Contattaci per supporto o feedbacks</i>

noperms: 
  "en": "âš ï¸ You don't have any permissions"
  "it": "âš ï¸ Non hai il permesso"


## BUTTONS ##

spawnrangefast_button:
  "en": "ğŸ”´ Fast: 25 - 45"
  "it": "ğŸ”´ Veloce: 25 - 45"

spawnrangemedium_button:
  "en": "ğŸŸ¡ Normal: 45 - 65"
  "it": "ğŸŸ¡ Normale: 45 - 65"
  
spawnrangeslow_button:
  "en": "ğŸŸ¢ Slow: 65 - 85"
  "it": "ğŸŸ¢ Lento: 65 - 85"
  
eng_button:
  "en": "English ğŸ‡¬ğŸ‡§"
  "it": "English ğŸ‡¬ğŸ‡§"
  
ita_button:
  "en": "Italiano ğŸ‡®ğŸ‡¹"
  "it": "Italiano ğŸ‡®ğŸ‡¹"
  
right_button:
  "en": "â¡ï¸"
  "it": "â¡ï¸"
  
left_button:
  "en": "â¬…ï¸"
  "it": "â¬…ï¸"

sort_button_id:
  en: "ğŸ“– Sort: ID"
  it: "ğŸ“– Ordina: ID"

sort_button_alphabetical:
  en: "ğŸ“– Sort: Alphabetic"
  it: "ğŸ“– Ordina: Alfabetico"

redcoin_button:
  "en": "ğŸ”´ Brave"
  "it": "ğŸ”´ Audace"
  
yellowcoin_button:
  "en": "ğŸŸ¡ Mysterious"
  "it": "ğŸŸ¡ Misterioso"
  
orangecoin_button:
  "en": "ğŸŸ  Tough"
  "it": "ğŸŸ  Tosto"
  
pinkcoin_button:
  "en": "ğŸ©· Charming"
  "it": "ğŸ©· Splendido"
  
greencoin_button:
  "en": "ğŸŸ¢ Heartful"
  "it": "ğŸŸ¢ Generoso"
  
bluecoin_button:
  "en": "ğŸ”µ Shady"
  "it": "ğŸ”µ Oscuro"
  
purplecoin_button:
  "en": "ğŸŸ£ Eerie"
  "it": "ğŸŸ£ Spaventatutti"
  
skybluecoin_button:
  "en": "ğŸ©µ Slippery"
  "it": "ğŸ©µ Sfuggente"
  
onestarcoin_button:
  "en": "â­ 1 Star Coin"
  "it": "â­ Moneta 1 Stella"
  
fivestarcoin_button:
  "en": "âœ¨ 5 Star Coin"
  "it": "âœ¨ Moneta 5 Stelle"
  
specialcoin_button:
  "en": "ğŸŒ€ Special Coin"
  "it": "ğŸŒ€ Moneta Speciale"
  
spawnranges_button:
  "en": "SpawnRanges ğŸš¦"
  "it": "SpawnRanges ğŸš¦"
  
languages_button:
  "en": "Language ğŸ‡¬ğŸ‡§/ğŸ‡®ğŸ‡¹"
  "it": "Lingua ğŸ‡¬ğŸ‡§/ğŸ‡®ğŸ‡¹"
  
contacts_button:
  "en": "Support/Credits ğŸ›ï¸"
  "it": "Supporto/Crediti ğŸ›ï¸"
  
closesettings_button:
  "en": "Close âŒ"
  "it": "Chiudi âŒ"
  
backtosettings_button:
  "en": "Back ğŸ”™"
  "it": "Indietro ğŸ”™"